### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by Nopik** [ThreeDotsLabs/wild-workouts-go-ddd-example#17]
The min & max are reversed: https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example/blob/ef82c2b75b42b34eb86e393030051275a53b083b/internal/trainer/domain/hour/hour.go#L58

**Comment by roblaszczak** [comment]
Fixed in 6954ccbd :wink: Thanks for noticing that!
