### ISSUE TITLE
Can't find a license

### ISSUE THREAD

**Issue by resnickmicah** [ThreeDotsLabs/wild-workouts-go-ddd-example#29]
I see in @blaggacao 's comment on #9 that he cited the license for this repo as MIT, but I don't see a license file in the root directory. I did a search of the repo and didn't find any mention of a license either. Is this code MIT-licensed? If so, can you add a copy of the MIT license somewhere in the repository?

**Comment by m110** [comment]
Hey @resnickmicah, thank you for rising this. I'm not sure how we missed the license. 🤯  I've added it.
