### ISSUE TITLE
Aggregate Root > Package Oriented Design

### ISSUE THREAD

**Issue by wlopez-enkoding** [ThreeDotsLabs/wild-workouts-go-ddd-example#32]
Hi guys 👋 

First of all: what a great material this GitHub project, has helped me a lot, thanks for that 🙏 

My question: is ok that a domain entity could call another domain entity at the same level ? I'm trying to refactor a project I have, and the concept of **Aggregate Root** was working fine, but now I want to separate them and I'm a little confused about how implement it under this new concept.

**Comment by m110** [comment]
Hey @wlopez-enkoding!

Do you mean two entities interacting within the same domain? Sure, it's fine. Just watch out if they need to be transactionally consistent. Also, never reach out to an external domain package. 🙂

**Comment by wlopez-enkoding** [comment]
> Hey @wlopez-enkoding!
> 
> Do you mean two entities interacting within the same domain? Sure, it's fine. Just watch out if they need to be transactionally consistent if you make any changes. Also, never reach out to an external domain package. 🙂

In the case I want to reuse a package (or a domain context) should I consider moving /commons along then ?

**Comment by m110** [comment]
If you need to use a common package between two domains, I would stop and think whether they are correctly separated.

It depends on what you want to reuse. If you have `orders` and `invoices` domains and both use a generic type, like `Money`, it would make sense to extract it to a separate package.

On the other hand, if your `invoices` domain needs to use `Order` from `orders`, something is wrong. Perhaps the domains shouldn't be separated at all because they use the same concepts. Or maybe `Invoice` should use a projection of `Order`, not the exact type.

In general, a need to import a non-generic type from another domain means something's wrong with the boundaries.

I can add more specific advice if you share more about your domain. 🙂

**Comment by frederikhors** [comment]
I can't wait for your post about strategic patterns, @m110!

**Comment by wlopez-enkoding** [comment]
> If you need to use a common package between two domains, I would stop and think whether they are correctly separated.
> 
> It depends on what you want to reuse. If you have `orders` and `invoices` domains and both use a generic type, like `Money`, it would make sense to extract it to a separate package.
> 
> On the other hand, if your `invoices` domain needs to use `Order` from `orders`, something is wrong. Perhaps the domains shouldn't be separated at all because they use the same concepts. Or maybe `Invoice` should use a projection of `Order`, not the exact type.
> 
> In general, a need to import a non-generic type from another domain means something's wrong with the boundaries.
> 
> I can add more specific advice if you share more about your domain. 🙂

Not sure if image below is self-descriptive, but for example... in the Order in need to use and slice of Products... but before I understood I need to separate concepts at the same level. I'm doing it right ?


<img width="801" alt="Screen Shot 2021-07-14 at 20 40 21" src="https://user-images.githubusercontent.com/9939892/125710290-60e7deaa-e5fc-4fcb-9ef6-23dca090edfa.png">

**Comment by wlopez-enkoding** [comment]
What makes noice to me is the fact that if make that link, then I can't just move order to another project, because it as a dependency. Should I put all together then ?

**Comment by wlopez-enkoding** [comment]
as additional information I can say that a loading sheet has many orders, and an order has many products associated...

**Comment by m110** [comment]
Hey! So it seems you have similar situation as @frederikhors described in https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example/issues/30

I'm afraid the current structure of Wild Workouts can be a bit misleading, as we didn't explore splitting domains and bounded contexts yet. 

Looking at your example, it seems you've split the project based on domain entities. But it's likely all of them are part of the dame domain. 

Try keeping a single separation of domain/app/ports/adapters for now. If all entities are strongly coupled, this will be more natural to work with. 

Or course, there are situations where entities from separate services refer to each other. But you should never import another domain directly, there are more advanced patterns to achieve it.

**Comment by wlopez-enkoding** [comment]
Thank you @m110 !
