### ISSUE TITLE
Maybe a better name for internal would be services

### ISSUE THREAD

**Issue by aruntj** [ThreeDotsLabs/wild-workouts-go-ddd-example#33]
First off this is an amazing project. This is one of those rare gems that you find on the internet. I've gone through all the articles and am using this repo as a boilerplate for my project. So thank you so much!!!

I did have an observation to make. It seems to me that the folder `internal` ought to be called `services` since it in fact holds the different services - `users`, `trainer` and `trainings`. Each of the services can also be published under `github.com/ThreeDotsLabs/wild-workouts-go-ddd-example/services/...`.  `common` could be a separate package under `services` that is dependancy of the other 3 services. 

What do you think?

**Comment by m110** [comment]
Hey @aruntj!

Thank you for the comment, I'm really glad the articles were helpful!

It's a good point. We usually stick to `internal` as the Go compiler treats this package in a special way, not allowing anything external to import stuff from it. It's usually a good idea for services, so they can't refer to each other's core. 

Your suggestion fits the purpose. We're planning more refactoring on the project, so it's not clear yet what we'll arrive at in the end.

Definitely use what makes the most sense in your project. Wild Workouts is a bit unusual as we keep a few services in one repository. 🙂

**Comment by aruntj** [comment]
I didn't know that go treats `internal` differently, good to know. Can't wait for the next round of refactoring 🙂
