### ISSUE TITLE
Failing to run at docker-compose up - page 10 in the book. 

### ISSUE THREAD

**Issue by hughsheehy** [ThreeDotsLabs/wild-workouts-go-ddd-example#34]
Trying to follow the instructions on page 10 of the book. 

Docker is running. Compose is running (all the one on Windows 10)

I run docker-compose up 

I get a loooong series of outputs in the terminal.  The only error message I can see is this. 

**

> web_1                        | /start.sh: set: line 1: illegal option -
> wild-workouts-go-ddd-example_web_1 exited with code 2

**

There are a few warnings, but that seems to be the only error. The web_1 service is also not running. If I CTRL-C, the other services all shut down. Web_1 does not say it's shutting down. It seems to have died at that error.

**Comment by m110** [comment]
Hey. We didn't test the setup on Windows, perhaps that's the issue. Although the `start.sh` should be executed within a Linux container anyway. 🤔 Did you find a way around it?

**Comment by joanna-liana** [comment]
@hughsheehy I've come across the same issue. Even though the script is run in the container, it has a wrong EOL format (CR LF). The trick is to simply change it to LF (using Notepad++ or VSCode), then delete the `wild-workouts-go-ddd-example_web` image and run `compose` again.

Also, this problem can be avoided in the first place if you `git clone` the project directly into WSL (all files will have the correct LF endings)
