### ISSUE TITLE
Possibly violating SRP

### ISSUE THREAD

**Issue by msamoylov** [ThreeDotsLabs/wild-workouts-go-ddd-example#5]
The single-responsibility principle might be violated here. Not sure if the `NewTraining` function should be doing validation routines.

https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example/blob/22c0a25b67c4669d612a2fa4a434ffae8e35e65a/internal/trainings/domain/training/training.go#L25

**Comment by roblaszczak** [comment]
Actually, it is expected 😉 

This is ensuring that ["The Second Rule of DDD lite: always keep a valid state in the memory
"](https://threedots.tech/post/ddd-lite-in-go-introduction/#the-second-rule-always-keep-a-valid-state-in-the-memory) is met.
