### ISSUE TITLE
Failed to create shim task: OCI runtime create failed

### ISSUE THREAD

**Issue by matthew-walter-works** [ThreeDotsLabs/wild-workouts-go-ddd-example#60]
## Summary 
- `docker-compose up` fails due to a `Failed to create shim task: OCI runtime create failed` error

## Setup
- MacOS: Big Sur 11.6.6
- Docker Desktop, with the setting "Use Docker Compose V2"
        ![image](https://user-images.githubusercontent.com/15617370/172477672-91d5f9d6-4e8e-4cf1-9f23-2de693fa2f31.png)
- `docker-compose -v` = v2.6.0 (needed to the https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example/blob/4cc4ad70c2051ff31c7a20e8d5abe26b5dacd3fb/docker-compose.yml#L1)

## Steps To Reproduce:
- clone [wild-workouts-go-ddd-example](https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example)
- run `docker-compose up`

## Result:
```bash
...
wild-workouts-web-1                        | + yarn install
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./start.sh": permission denied: unknown
```

**Comment by m110** [comment]
Should be fixed by #59 :)

**Comment by matthew-walter-works** [comment]
@m110 thanks for the quick response, however the issue is still open and am getting the same error after re-cloning repo.

**Comment by matthew-walter-works** [comment]
> Should be fixed by #59 :)

@m110 This is not fixed yet

**Comment by matthew-walter-works** [comment]
@m110 oh no, that was it? I missed the docker-compose build? I am sorry Miłosz. I looked at https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example/commit/b519c611e9d1248a149c89db9bcf879fd78b1e35 and it seems to be an empty commit so I am assuming it was me.

**Comment by matthew-walter-works** [comment]
thank you for the help! and great job on the series, I have really enjoyed it!

**Comment by m110** [comment]
No worries! The commit includes the executable flag for `start.sh`. I mentioned the docker-compose build as it doesn't run automatically and you could miss the changes. 🙂
