### ISSUE TITLE
Trying to understand the code: where can I find the routing info

### ISSUE THREAD

**Issue by suntong** [ThreeDotsLabs/wild-workouts-go-ddd-example#73]
Trying to understand the repo code.
Where can I find the routing info?

https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example/blob/56ef6d5daa2e1f2de82f85278eef1fe5825eb401/api/openapi/trainer.yml#L17-L18

Say for above `/trainer/calendar`, where can I find the routing Go code to link from endpoint to go function?

E.g., for normal Chi API, it'll be something like:

```go
router := chi.NewRouter()

router.Get("/", func(writer http.ResponseWriter, request *http.Request) {
	. . .
})
```

But I'm not able to find any `router.Get` related Go code in the entire repo.
Please help.

**Comment by asteria-jacky** [comment]
I think the handler and the interface are generated by code generator.
https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example/blob/56ef6d5daa2e1f2de82f85278eef1fe5825eb401/internal/trainer/ports/openapi_api.gen.go#L157-L159
