### ISSUE TITLE
Lincense of this code

### ISSUE THREAD

**Issue by blaggacao** [ThreeDotsLabs/wild-workouts-go-ddd-example#9]
I want to attribute proper authorship and SPDX-License-Identifier for code that I'm adopting from the `./internal/common` and other packages. I would be going with:

```golang
// Copyright © 2020 Miłosz Smółka <hmilosz@threedotslabs.com>
// Copyright © 2020 Robert Laszczak <robert@threedotslabs.com>
// SPDX-License-Identifier: MIT
```

Please let me know if that is fine or if there are any objections.

**Comment by m110** [comment]
Seems correct, apart from a typo in my e-mail address. 😁

**Comment by resnickmicah** [comment]
I see in @blaggacao 's comment that he identifies the license for this repo as MIT, but I don't see a license file in the root director.? I did a search of the repo and didn't find any mention of a license either. Is this code MIT-licensed? If so, can you add a copy of it to the root of this repository?
